@startmindmap
'https://plantuml.com/mindmap-diagram


* 工作职责
** 验收需求
*** 预习原型
**** 流程是否完善
**** 定义是否清晰
**** 设计图和原型是否一致
**** 记录疑问
**** 预想实现方案
*** 产品会议
**** 提出疑问
**** 提出方案
*** 检验原型
**** 落实解决问题的方案
** 设计
*** 架构设计
*** 数据库设计
*** 接口设计
** 计划
*** 拆分任务
*** 设定时间
**** 子任务工时小于一天
*** 调整计划
** 编码
*** 接口设计图
*** 编码
*** 单元测试
** 联调
*** 积极响应
** 测试
*** 使用APP
*** 核对数据
*** 优化代码
** 部署
*** 部署文档
** 维护
*** 查看日志
*** 数据核对
@endmindmap
